<a href="https://colab.research.google.com/github/Varun7860dixit/NumPy_Practice/blob/main/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Write a program to create a 3x3 NumPy array filled with random integers between 1 and 50. Print the array and its shape.

In [ ]:
import numpy as np
arr = np.random.randint(1,51,size=(3,5))
print(arr)
print(arr.shape)

[[ 7 47 12 17 13]
 [47 16 11  5 23]
 [41 48 19 29 26]]
(3, 5)


####2. Create a 5x5 NumPy array with values ranging from 1 to 25. Extract:
*   The first row
*   The last column
*   The sub-array from index [1:4, 1:4]

In [ ]:
import numpy as np
arr = np.random.randint(1,26,size=(5,5))
print("Array: \n",arr)
print("First Row: \n",arr[0])
print("Last Column: \n",arr[:,-1])
print("Sub-Array: \n",arr[1:4,1:4])

Array: 
 [[ 1 12 18  2  8]
 [ 1 20 23 21  7]
 [23 10  4  9 15]
 [ 9 17 14  7  3]
 [16  4 12  9 19]]
First Row: 
 [ 1 12 18  2  8]
Last Column: 
 [ 8  7 15  3 19]
Sub-Array: 
 [[20 23 21]
 [10  4  9]
 [17 14  7]]


####3. Generate a NumPy array with 10 random floating-point numbers. Compute and print:
*   The mean, median, and standard deviation of the array
*   An array with each element squared

In [ ]:
import numpy as np
arr = np.random.rand(10)
print("Array: \n",arr)
print("Standard Deviation of the array: ",np.std(arr))
print("Mean of the array: ",np.mean(arr))
print("Median of the array: ",np.median(arr))
print("Sqr_Array: \n",arr**2)

Array: 
 [0.00729695 0.7140573  0.89147985 0.27679996 0.33516703 0.70159621
 0.89313209 0.8953134  0.62313095 0.81200889]
Standard Deviation of the array:  0.29164238255505265
Mean of the array:  0.6149982601563421
Median of the array:  0.7078267506534599
Sqr_Array: 
 [5.32454578e-05 5.09877822e-01 7.94736319e-01 7.66182155e-02
 1.12336935e-01 4.92237235e-01 7.97684934e-01 8.01586076e-01
 3.88292180e-01 6.59358431e-01]


#### 4. Create two 3x3 arrays with random integers. Perform and print the results of:
*   Element-wise addition
*   A dot product of the two arrays

In [ ]:
import numpy as np
mat1 = np.random.randint(1,50,size=(3,3))
mat2 = np.random.randint(2,40,size=(3,3))
print("Matrix 1: \n",mat1,"\n","Matrix 2: \n",mat2)
print("Sum of two Matrix: \n",mat1+mat2)
print("Multiplication of two Matrix: \n",np.dot(mat1,mat2))

Matrix 1: 
 [[ 3 32 44]
 [29 28  9]
 [ 1 43 22]] 
 Matrix 2: 
 [[16 18 37]
 [23 30 38]
 [33  9 32]]
Sum of two Matrix: 
 [[19 50 81]
 [52 58 47]
 [34 52 54]]
Multiplication of two Matrix: 
 [[2236 1410 2735]
 [1405 1443 2425]
 [1731 1506 2375]]


####5. Create a 1D array with 15 random integers between 10 and 100. Extract all numbers that are:
*   Greater than 50
*   Divisible by 5

In [ ]:
import numpy as np
arr = np.random.randint(10,100,size=(15))
print("Array: ",arr)
print("Greater than 50: ",arr[arr>50])
print("Divisible by 5: ",arr[(arr%5==0)])

Array:  [79 70 50 73 14 27 19 40 39 87 54 67 87 24 61]
Greater than 50:  [79 70 73 87 54 67 87 61]
Divisible by 5:  [70 50 40]


####6. Create a 1D array of size 12 with numbers from 1 to 12. Reshape it into a 3x4 array. Add a 1D array [10, 20, 30, 40] to each row using broadcasting.

In [ ]:
import numpy as np
arr = np.random.randint(1,13,size=(12))
print("Original_Array: ",arr)
arr1 = arr.reshape(3,4)
print("Reshaped_Array: \n",arr1)
arr2 = np.array([10,20,30,40])
sum = arr1 + arr2
print("After add a 1D array [10, 20, 30, 40] to each row using broadcasting: \n",sum)

Original_Array:  [ 2  3  2  5  3 12  3  6  6  7  9  9]
Reshaped_Array: 
 [[ 2  3  2  5]
 [ 3 12  3  6]
 [ 6  7  9  9]]
After add a 1D array [10, 20, 30, 40] to each row using broadcasting: 
 [[12 23 32 45]
 [13 32 33 46]
 [16 27 39 49]]


####7. Create a 3x3 matrix and compute its:
*   Transpose
*   Determinant
*   Inverse (if it exists)

In [ ]:
import numpy as np
mat = np.matrix([[4,2,7],[1,8,2],[0,7,9]])
print("Original_Matrix: \n",mat)
print("Transpose of Matrix: \n",mat.T)
#print("Transpose of Matrix: \n",np.transpose(mat))
print("Determinant of Matrix: ",np.linalg.det(mat).round())
print("Inverse of Matrix: \n",np.linalg.inv(mat))

Original_Matrix: 
 [[4 2 7]
 [1 8 2]
 [0 7 9]]
Transpose of Matrix: 
 [[4 1 0]
 [2 8 7]
 [7 2 9]]
Determinant of Matrix:  263.0
Inverse of Matrix: 
 [[ 0.22053232  0.11787072 -0.19771863]
 [-0.03422053  0.13688213 -0.00380228]
 [ 0.02661597 -0.10646388  0.11406844]]


####8. Create a 1D array of 20 random integers. Replace all elements greater than 50 with -1 using np.where().

In [ ]:
import numpy as np
arr = np.random.randint(1,100,size=(20))
print("Orginal_Array: ",arr)
modified_arr = np.where(arr>50,-1,arr)
print("Modified_Array: ",modified_arr)

Orginal_Array:  [37 51  4 19 79 34 13 67 16 50 53 49 19 17 59 26 50 36 13 41]
Modified_Array:  [37 -1  4 19 -1 34 13 -1 16 50 -1 49 19 17 -1 26 50 36 13 41]


####9. Generate a 1D array of 10 random integers. Sort the array in ascending order and find the index of the number closest to 25.

In [ ]:
import numpy as np
arr = np.random.randint(1,100,size=(10))
print("Orginal_Array: ",arr)
sorted_arr = np.sort(arr)
print("Sorted_Array: ",sorted_arr)
find = np.searchsorted(sorted_arr,25)
print("The index of the number closest to 25: ",find-1)

Orginal_Array:  [99 21 87  9 64 76 52 94 83 50]
Sorted_Array:  [ 9 21 50 52 64 76 83 87 94 99]
The index of the number closest to 25:  1


####10. Write a custom function that takes a 1D NumPy array and returns an array with each element increased by 10 if the element is even and decreased by 5 if it is odd. Test the function on a random array.

In [ ]:
import numpy as np
def modify_array(arr):
  modified_array = np.where(arr%2==0,arr+10,arr-5)
  return modified_array
arr = np.random.randint(1,50,size=(10))
modified_arr = modify_array(arr)
print("Orginal_Array: ",arr)
print("Modified_Array: ",modified_arr)

Orginal_Array:  [40 32 41 16 14 47 48 25 21 47]
Modified_Array:  [50 42 36 26 24 42 58 20 16 42]


####11. Write a program to create a NumPy array with 20 random integers between 1 and 10. Find and print:
*   The unique elements in the array.
*   The count of each unique element.

In [ ]:
import numpy as np
arr = np.random.randint(1,10,size=(20))
arr1 = np.unique(arr,return_counts=True)
print(arr)
print(arr1)

[5 6 1 5 6 8 4 6 6 2 4 6 2 9 2 4 4 5 3 6]
(array([1, 2, 3, 4, 5, 6, 8, 9]), array([1, 3, 1, 4, 3, 6, 1, 1]))


####12. Write a NumPy program to create a 6×6 matrix with random integers between 1 and 100. Replace all elements that are divisible by 3 with their negative values.

In [ ]:
import numpy as np
mat = np.random.randint(1,100,size=(6,6))
print("Original_Matrix: \n",mat)
modified_mat = np.where(mat%3==0,-mat,mat)
print("Modified_Matrix: \n",modified_mat)

Original_Matrix: 
 [[27 15 96 94 12 66]
 [32 31  5 16 38 33]
 [44 25 91 57  1 50]
 [91 41 93  3 82 71]
 [84  8 62 13 69 61]
 [61 23 19 58 64 62]]
Modified_Matrix: 
 [[-27 -15 -96  94 -12 -66]
 [ 32  31   5  16  38 -33]
 [ 44  25  91 -57   1  50]
 [ 91  41 -93  -3  82  71]
 [-84   8  62  13 -69  61]
 [ 61  23  19  58  64  62]]


##**NumPy Combined Challenge**

You are given the task of analyzing a dataset using NumPy. Follow the steps below to complete the challenge:

###**1. Create Data**
*  Generate a 6×6 matrix of random integers between 10 and 100.
*  Extract the third row and store it in a separate variable.

###**2. Data Manipulation**
*  Replace all even numbers in the matrix with -1.
*  Reshape the matrix into a 3×12 array.

###**3. Mathematical Operations**
*  Compute the mean, median, and standard deviation of the reshaped array.
*  Normalize the matrix (scale values between 0 and 1).

###**4. Linear Algebra Operations**
*  Extract the diagonal elements of the original 6×6 matrix.
*  Compute the dot product of the diagonal elements with themselves.
*  If the original matrix is invertible, find its inverse and determinant.

###**5. Boolean Operations**
*  Create a mask that selects all values greater than the mean of the matrix.
*  Count how many values are greater than the mean.

###**6. Sorting & Unique Values**
*  Find and print all unique values in the matrix.
*  Sort the matrix along each row in ascending order.

In [ ]:
import numpy as np
arr = np.random.randint(10,100,(6,6))
mat = np.matrix(arr)
third_row = mat[3,:]
print("Matrix: \n",mat)
print("Third Row: ",third_row)
updated_mat = np.where((mat%2==0),-1,mat)
updated_mat = np.reshape(updated_mat,(3,12))
print("Updated Matrix: \n",updated_mat)

mean = np.mean(updated_mat).round(2)
median = np.median(updated_mat).round(2)
standard_deviation = np.std(updated_mat).round(2)
print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",standard_deviation)
min_val = np.min(updated_mat)
max_val = np.max(updated_mat)
normalized_matrix = (updated_mat - min_val) / (max_val - min_val)
print("Normalized Matrix: \n",normalized_matrix)

diagonal_elements = np.diagonal(mat)
print("Diagonal Elements: ",diagonal_elements)
dot_product = np.dot(diagonal_elements,diagonal_elements)
print("The dot product of the diagonal elements with themselves:",dot_product)

determinant = np.linalg.det(mat)
if(determinant!=0):
  inverse = np.linalg.inv(mat)
  print("Inverse of matrix: \n",inverse)
  print("Determinant of matrix: ",determinant.round(2))
else:
  print("Matrix is not Invertible");

mask = mat[mat>mat.mean()]
print("All values greater than the mean of the matrix: ",mask)
print("Count of values those are greater than the mean: ",mask.size)

uni_val = np.unique(mat)
print("Unique values of matrix: ",uni_val)
sorted_mat = np.sort(mat)
print("Sorted Matrix: \n",sorted_mat)

Matrix: 
 [[90 40 37 50 72 83]
 [45 88 34 34 48 96]
 [17 78 12 87 59 52]
 [19 15 67 88 74 69]
 [88 62 63 55 42 35]
 [69 47 75 34 24 37]]
Third Row:  [[19 15 67 88 74 69]]
Updated Matrix: 
 [[-1 -1 37 -1 -1 83 45 -1 -1 -1 -1 -1]
 [17 -1 -1 87 59 -1 19 15 67 -1 -1 69]
 [-1 -1 63 55 -1 35 69 47 75 -1 -1 37]]
Mean:  23.89
Median:  -1.0
Standard Deviation:  30.33
Normalized Matrix: 
 [[0.         0.         0.43181818 0.         0.         0.95454545
  0.52272727 0.         0.         0.         0.         0.        ]
 [0.20454545 0.         0.         1.         0.68181818 0.
  0.22727273 0.18181818 0.77272727 0.         0.         0.79545455]
 [0.         0.         0.72727273 0.63636364 0.         0.40909091
  0.79545455 0.54545455 0.86363636 0.         0.         0.43181818]]
Diagonal Elements:  [90 88 12 88 42 37]
The dot product of the diagonal elements with themselves: 26865
Inverse of matrix: 
 [[ 0.03007628 -0.02651184  0.02440662 -0.02194362 -0.04662002  0.0520398 ]
 [-0.03110877 